### PR TITLE
Add share category

### PR DESCRIPTION
**Pull request by Rytiggy**
- To install a local node on your computer enter `sudo npm install --unsafe-perm -g <path to node>`
    - *I needed to use `sudo & --unsafe-perm -g` as it was throwing errors without it*
- In our case our custom nodes are stored in `./nodes`
- To add custom nodes to the share category set the category to `share` in the html file of your custom node
- To add the Share icon to your custom node add a `directory` called `icons` alongside its `.js` and `.html` files with the share.png icon in it.
    - download the Share icon here: [Share.png](https://i.ibb.co/Z8PYj5b/share.png)
- share category

## Notes
- As a note Share nodes will not show up unless you have them installed. We should compile a list of all the share nodes so they can be dependencies on the repo by default
- share node example

### CODE REVIEW

**Comment by h-parekh** [comment]
I assume you were working through an example and iterated this over time. Consider using a more contextual name for the **_Node-red-node-example_** dir. We could have more custom nodes in the future, using a prefix like _share-_  may make sense?

So in this case it could be _share-lower-case_. Thoughts?

**Comment by Rytiggy** [comment]
Seems like a good structure to follow ill update the PR to reflect it!

**Comment by h-parekh** [comment]
I was also thinking if we need to add an additional step in the [quick start](https://github.com/share-research/share-red#quick-start) section of readme for installing share nodes.

**Comment by Rytiggy** [comment]
Also a good idea, I think we could take it a step further and have a script that can be run *which would be noted in the quick start guide* that would automatically add all the share nodes that we offer.

**Comment by Rytiggy** [comment]
Approved by @h-parekh

**Pull request merged**
